backendId: "0191ae7b-ff5a-7b1f-9b1e-b7d1c0b7842c"
externalUrl: "http://localhost:3001"
ua_root_cert_path: null
ua_root_private_key_path: null
ua_intermediate_cert_path: null
ua_intermediate_private_key_path: null
signingKeys:
  activeKid: "k1"
  keys:
    - kid: "k1"
      alg: "EdDSA"
      privateKey: "MC4CAQAwBQYDK2VwBCIEIHZpmqe4EtA0jQE3mUYxPRRJRGgBTQhji+GkGU/Mymob"
      publicKey: "MCowBQYDK2VwAyEAwDqa+NOeBFlf79vbtbzh7N+58zMqC/4/TZKtNKZ9y3o="
security:
  apiSecretHeader: "x-ua-api-secret"
  jwt:
    accessTtlMinutes: 15
    refreshTtlDays: 30
